package actv.ccs.rules.start;

import actv.ccs.model.ConvictCichlid;
import actv.ccs.model.type.FishState;
import actv.ccs.fact.CoolingDown;


rule "Cooldown"
	ruleflow-group "swim"

	when
		not (exists CoolingDown());

		$cc : ConvictCichlid( state == FishState.CAUTION,
							  speed != baseSpeed,
							  $baseSpeed : baseSpeed );
					
	then
		modify($cc){
			setSpeed($baseSpeed),
			setState(FishState.IDLE);
		}
end