package actv.ccs.rules.start;


import actv.ccs.fact.Auditor;
import actv.ccs.model.ConvictCichlid;
import actv.ccs.model.type.FishState;
import actv.ccs.fact.CoolingDown;




rule "Cooling Down"
	ruleflow-group "swim"
	timer(int: 2s)
	
	when
		$auditor : Auditor()
		$cc : ConvictCichlid(state == FishState.CAUTION)
		
		$cd : CoolingDown( convictCichlid == $cc)
	then
		retract($cd);
		
		modify($cc){
			setCautionLevel($cc.getBaseCautionLevel()),
			setState(FishState.IDLE);
		}
		
		modify($auditor){
			getRulesFired().add(drools.getRule().getName());
		}
end