package actv.ccs.rules.start;


import actv.ccs.model.ConvictCichlid;
import actv.ccs.model.type.FishState;


rule "Initialize Cichlid"
	ruleflow-group "swim"
	salience 1000000

	when
		$cc : ConvictCichlid(	
					(baseCautionLevel == 0 ||
					baseSpeed == 0 ||
					baseAggroLevel == 0),
					state == FishState.NONE );
					
	then
		modify($cc){
			setBaseCautionLevel(5f),
			setBaseSpeed(4f),
			setBaseAggroLevel(2f),
			setState(FishState.IDLE);
		}
end