package actv.ccs.rules.idle;

import actv.ccs.model.ConvictCichlid;
import actv.ccs.model.type.FishState;
import actv.ccs.fact.CoolingDown;

global org.slf4j.Logger logger
global actv.ccs.fact.PRNG prng

rule "Idle"
	ruleflow-group "swim"
	
	// Fire every 2 seconds
	timer(int: 2s)

	when
		$cc : ConvictCichlid( state == FishState.IDLE,
							  $iwt : idleWaitTime);
		
	then
		modify($cc){
			setIdleWaitTime($cc.getIdleWaitTime + 1);
		}
		logger.info("PRNG: {}", prng.randomDouble());
		
end


