package actv.ccs.rules.idle;

import actv.ccs.sageTest.MoveActionFactory;
import actv.ccs.model.ConvictCichlid;
import actv.ccs.model.type.FishState;
import actv.ccs.fact.PRNG;

global org.slf4j.Logger logger

rule "Make Swim"
	ruleflow-group "swim"
	
	when
		PRNG($prng : prng)
		$cc : ConvictCichlid(state == FishState.IDLE, 
							 speed == 0,
							 $prng.nextDouble() < .3 )
	then
		$cc.setSpeed($cc.getBaseSpeed());		
		update($cc);
		logger.debug("Preparing to swim: " + $cc.getSpeed());
end