package actv.ccs.rules.idle;

import actv.ccs.sageTest.MoveActionFactory;
import actv.ccs.model.ConvictCichlid;
import actv.ccs.model.type.FishState;
import actv.ccs.fact.Auditor;
import java.util.Random;


rule "Move"
	ruleflow-group "swim"
	
	// Chance to move every 4 seconds
	timer(int: 3s)
	
	when
		$auditor :  Auditor()
		
		$cc : ConvictCichlid( state == FishState.IDLE,
							  $dir : direction);
		
	then
		Random r = new Random(System.currentTimeMillis());
		double p = r.nextDouble();
		System.out.println("Move: " + p);
		
		if(p < .30){
			if(r.nextBoolean)
				MoveActionFactory.turn($cc, 30);
			else
				MoveActionFactory.turn($cc, -30);
			update($cc);
				
			System.out.println("Turned 30 degrees!");
			
			modify($auditor){
				getRulesFired().add(drools.getRule().getName());
			}
		}else{
			System.out.println("No Movement");
		}
end


