package actv.ccs.rules.idle;

import actv.ccs.sageTest.MoveActionFactory;
import actv.ccs.model.ConvictCichlid;
import actv.ccs.fact.MoveCounter;
import sage.scene.SceneNode;

global org.slf4j.Logger logger

rule "Move"
	ruleflow-group "swim"
	timer(int: 100ms)
	when
		$cc : ConvictCichlid( )
							  
		$mc : MoveCounter(	convictCichlid == $cc, 
							$counter : counter, 
							direction != 0,
							$dir : direction)
		
	then
		if($counter > 0){
			MoveActionFactory.turn((SceneNode)$cc, $mc.getCounter() * $dir);
			update($cc);
			
			$mc.decrement();
			update($mc);
			logger.debug("Fired rule: [ {} ]", drools.getRule().getName());
		}
		
end


