package actv.ccs.rules.idle;

import actv.ccs.sageTest.MoveActionFactory;
import actv.ccs.model.ConvictCichlid;
import actv.ccs.model.type.FishState;
import java.util.Random;


global org.slf4j.Logger logger

rule "Move"
	ruleflow-group "swim"
	
	// Chance to move every 2 seconds
	timer(int: 2s)
	
	when
		$cc : ConvictCichlid( state == FishState.IDLE,
							  $dir : direction)
		
	then
		Random r = new Random(System.currentTimeMillis());
		double p = r.nextDouble();
		logger.debug("Move: " + p);
		
		if(p < .30){
			if(r.nextBoolean)
				MoveActionFactory.turn($cc, 30);
			else
				MoveActionFactory.turn($cc, -30);
			update($cc);
				
			logger.debug("Turned 30 degrees!");
			
		}else{
			logger.debug("No Movement");
		}
end


