package actv.ccs.rules.idle;

import actv.ccs.sageTest.MoveActionFactory;
import actv.ccs.model.ConvictCichlid;
import actv.ccs.model.type.FishState;
import graphicslib3D.Vector3D;
import sage.scene.SceneNode;


rule "Move To"
	ruleflow-group "swim"
	
	when
		$cc1 : ConvictCichlid( 	$aggroLevel1 : aggroLevel)
							  
		$cc2 : ConvictCichlid(	$dir2 : direction,
								aggroLevel >= $aggroLevel1,
								length < (MoveActionFactory.getDirection((SceneNode)$cc1, (SceneNode)this)).magnitude())
		
	then
		System.out.println(MoveActionFactory.getDirection($cc1, $cc2).magnitude());
		System.out.println($cc2.getLocation().getX() + "," + $cc2.getLocation().getY());
		
		Vector3D direction = MoveActionFactory.getDirection($cc1, $cc2);
		$cc2.setDirection(direction.normalize());
			
		MoveActionFactory.moveForward($cc2, $cc2.getSpeed());
		update($cc2);

end


