package actv.ccs.rules.idle;

import actv.ccs.sageTest.MoveActionFactory;
import actv.ccs.model.ConvictCichlid;
import actv.ccs.model.type.FishState;
import actv.ccs.fact.SwimCounter;
import sage.scene.SceneNode;

global org.slf4j.Logger logger

rule "Swim"
	ruleflow-group "swim"
	
	when
		$cc : ConvictCichlid()
		$sc : SwimCounter($counter : counter > 0)
	then
		
		//MoveActionFactory.moveForward((SceneNode)$cc, $cc.getSpeed());
		//update($cc);
		
		$sc.setCounter($counter-1);
		update($sc);
			
		logger.debug("Moving Forward: " + $cc.getSpeed());
end