package actv.ccs.rules.idle;

import actv.ccs.sageTest.MoveActionFactory;
import actv.ccs.model.ConvictCichlid;
import actv.ccs.model.type.FishState;
import java.util.Random;

global org.slf4j.Logger logger

rule "Swim"
	ruleflow-group "swim"
	
	timer(int: 2s)
	
	when
		$cc : ConvictCichlid(state == FishState.IDLE)
		
	then
		Random r = new Random();
		double p = r.nextDouble();
		logger.debug("Swim: " + p);
	
		
		if(p < .4){
			MoveActionFactory.moveForward($cc, $cc.getBaseSpeed());
			update($cc);
			logger.debug("Swimming forward...");
		}
		
end