package actv.ccs.rules.start;


import actv.ccs.model.ConvictCichlid;
import actv.ccs.model.type.FishState;
import actv.ccs.fact.CoolingDown;
import actv.ccs.fact.Auditor;


rule "Cooldown"
	ruleflow-group "swam"
	salience 100
	timer(int: 2s)

	when
		$auditor :  Auditor()
		
		$cc : ConvictCichlid(state == FishState.CAUTION)
					
		$cd : CoolingDown( convictCichlid == $cc);
	then
		retract($cd);
		
		modify($cc){
			setState(FishState.IDLE);
		}
		
		modify($auditor){
			getRulesFired().add(drools.getRule().getName());
		}
end