package actv.ccs.rules.start;

import actv.ccs.model.ConvictCichlid;
import actv.ccs.model.type.FishState;
import actv.ccs.fact.CoolingDown;
import actv.ccs.fact.Auditor;

rule "Start"
	ruleflow-group "swim"
	salience 10000

	when
		$auditor : Auditor();
		
		$cc : ConvictCichlid(	
					$baseCautionLevel : baseCautionLevel != null,
					$baseSpeed : baseSpeed != null,
					state == FishState.NONE,
					(cautionLevel != ($baseCautionLevel * 1.6f) || 
					 speed != ($baseSpeed * 1.6f)));
					
		not( exists CoolingDown(convictCichlid == $cc));
	then
		insert( new CoolingDown($cc, $baseCautionLevel * .5));
		modify($cc){
			setCautionLevel($baseCautionLevel * 1.6f),
			setSpeed($baseSpeed * 1.6f),
			setState(FishState.CAUTION);
		}
		modify($auditor){
			getRulesFired().add(drools.getRule().getName());
		}
end