package actv.ccs.rules.start;

import actv.ccs.model.ConvictCichlid;
import actv.ccs.model.type.FishState;
import actv.ccs.fact.CoolingDown;

rule "Start"
	ruleflow-group "start"
	salience 10000

	when
		$cc : ConvictCichlid(	
					state != FishState.CAUTION,
					$baseCautionLevel : baseCautionLevel != null,
					$baseCautionLevel != cautionLevel );
					
		not( exists CoolingDown(convictCichlid == $cc));
	then
		insert( new CoolingDown($cc, $baseCautionLevel * .5));
		modify($cc){
			setCautionLevel($baseCautionLevel * 1.6f),
			setState(FishState.CAUTION);
		}
end