package actv.ccs.rules.start;

import actv.ccs.model.ConvictCichlid;
import actv.ccs.model.type.FishState;
import actv.ccs.fact.CoolingDown;

rule "Start"
	ruleflow-group "start"
	salience 10000

	when
		$cc : ConvictCichlid(	
					$baseCautionLevel : baseCautionLevel != null,
					$baseSpeed : baseSpeed != null,
					(cautionLevel != ($baseCautionLevel * 1.6f) || 
					 speed != ($baseSpeed * 1.6f) ||
					 state != FishState.CAUTION));
					
		not( exists CoolingDown(convictCichlid == $cc));
	then
		insert( new CoolingDown($cc, $baseCautionLevel * .5));
		modify($cc){
			setCautionLevel($baseCautionLevel * 1.6f),
			setSpeed($baseSpeed * 1.6f),
			setState(FishState.CAUTION);
		}
end