package actv.ccs.rules.idle;

import actv.ccs.sageTest.MoveActionFactory;
import actv.ccs.model.ConvictCichlid;
import actv.ccs.model.type.FishState;
import actv.ccs.fact.Auditor;
import graphicslib3D.Vector3D;

rule "Move To"
	ruleflow-group "swim"
	
	when
		$auditor :  Auditor()
		
		$cc1 : ConvictCichlid( 	$aggroLevel1 : aggroLevel)
							  
		$cc2 : ConvictCichlid(	state == FishState.SWIM,
								$dir2 : direction,
								aggroLevel >= $aggroLevel1,
								length/2 < (MoveActionFactory.getDirection($cc1, this)).magnitude())
		
	then
		System.out.println(MoveActionFactory.getDirection($cc1, $cc2).magnitude());
		System.out.println($cc2.getLocation().getX() + "," + $cc2.getLocation().getY());
		
		Vector3D direction = MoveActionFactory.getDirection($cc1, $cc2);
		$cc2.setDirection(direction.normalize());
			
		MoveActionFactory.moveForward($cc2, $cc2.getSpeed());
		update($cc2);

		System.out.println(drools.getRule().getName());		
		modify($auditor){
			getRulesFired().add(drools.getRule().getName());
		}
end


