package actv.ccs.rules.idle;

import actv.ccs.sageTest.TestCichlid;
import actv.ccs.model.type.FishState;
import actv.ccs.fact.Auditor;
import java.util.Random;


rule "Move Test"
	ruleflow-group "swim"
	
	// Chance to move every 4 seconds
	timer(int: 4s)
	
	when
		$auditor :  Auditor()
		
		$cc : TestCichlid( state == FishState.IDLE,
							  $dir : direction);
		
	then
		Random r = new Random();
		double p = r.nextDouble();
		System.out.println("P: " + p);
		
		if(p < .30){
			if(r.nextBoolean)
				$cc.setDirection($dir+30);
			else
				$cc.setDirection($dir-30);
				
			System.out.println("Turned 30 degrees");
			
			modify($auditor){
				getRulesFired().add(drools.getRule().getName());
			}
		}else{
			System.out.println("No Movement");
		}
		update($cc);
end


