package actv.ccs.rules.idle;

import actv.ccs.model.ConvictCichlid;
import actv.ccs.model.type.FishState;
import actv.ccs.fact.CoolingDown;
import actv.ccs.fact.Auditor;
import actv.ccs.fact.IdleTimer;


rule "Idle"
	ruleflow-group "swim"
	salience 1000

	when
		$auditor :  Auditor()
		
		$cc : ConvictCichlid( state == FishState.IDLE,
							  idleWaitTime - System.currentTimeMillis() < 0,
							  $iwt : idleWaitTime);
		
//	$it : IdleTimer(convictCichlid == $cc, idleTime > ($iwt - System.currentTimeMillis()))
	then
		modify($cc){
			setIdleWaitTime(System.currentTimeMillis() + 4000);
		}
		
		modify($auditor){
			getRulesFired().add(drools.getRule().getName());
		}
		System.out.println($cc.getIdleWaitTime());
end