package actv.ccs.rules.idle;

import actv.ccs.model.ConvictCichlid;
import actv.ccs.model.type.FishState;
import actv.ccs.fact.CoolingDown;
import actv.ccs.fact.Auditor;
import actv.ccs.fact.IdleTimer;


rule "Idle"
	ruleflow-group "swim"
	
	// Fire every 2 seconds
	timer(int: 2s)

	when
		$auditor :  Auditor()
		
		$cc : ConvictCichlid( state == FishState.IDLE,
							  $iwt : idleWaitTime);
		
	then
		modify($cc){
			setIdleWaitTime($cc.getIdleWaitTime + 1);
		}
		
		modify($auditor){
			getRulesFired().add(drools.getRule().getName());
		}
end


