package actv.ccs.rules.idle;

import actv.ccs.model.ConvictCichlid;
import actv.ccs.model.type.FishState;
import actv.ccs.fact.Auditor;
import java.util.Random;


rule "Move"
	ruleflow-group "swim"
	timer(int: 2s)
	
	when
		$auditor :  Auditor()
		
		$cc : ConvictCichlid( state == FishState.IDLE,
							  $dir : direction);
		
	then
		Random r = new Random();
		double p = r.nextDouble();
		System.out.println("P: " + p);
		
		if(p < .30){
			if(r.nextBoolean)
				$cc.setDirection($dir+30);
			else
				$cc.setDirection($dir-30);
				
			System.out.println("Turned 30 degrees");
			
			modify($auditor){
				getRulesFired().add(drools.getRule().getName());
			}
		}else{
			System.out.println("No Movement");
		}
		update($cc);
end


